extends Node

signal OnGenericUIButtonClick
signal OnGenericMenuOpen
signal OnGenericMenuClose
signal OnMainMenuButton
signal OnCharacterSelectButton
signal OnGenericUIEvent

signal OnMainMenuOn
signal OnMainMenuOff
signal OnSelectionMenuOn
signal OnSelectionMenuOff